import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOrderSpecifications1771856103899 implements MigrationInterface {
    name = 'AddOrderSpecifications1771856103899'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_customer_created_by"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_order_customer"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_order_created_by"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" DROP CONSTRAINT "FK_production_job_order"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" DROP CONSTRAINT "FK_production_job_operator"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" DROP CONSTRAINT "FK_stock_transaction_item"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" DROP CONSTRAINT "FK_stock_transaction_created_by"`);
        await queryRunner.query(`ALTER TABLE "job_costs" DROP CONSTRAINT "FK_job_cost_job"`);
        await queryRunner.query(`ALTER TABLE "job_costs" DROP CONSTRAINT "FK_job_cost_item"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoice_order"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoice_customer"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_invoice_created_by"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_invoice_item_invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_customer_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_customer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_order_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_production_job_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_production_job_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_production_job_scheduled_start"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_item_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_inventory_item_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transaction_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_stock_transaction_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_cost_job"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_job_cost_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_customer"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invoice_item_invoice"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_product_type_enum" AS ENUM('cpp_carton', 'silvo_blister', 'bent_foil', 'alu_alu')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "product_type" "public"."orders_product_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "is_repeat_order" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "previous_order_id" uuid`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "card_size" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "strength" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "type" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "color_cmyk" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "color_p1" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "color_p2" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "color_p3" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "color_p4" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."orders_varnish_type_enum" AS ENUM('water_base', 'duck', 'plain_uv', 'spot_uv', 'drip_off_uv', 'matt_uv', 'rough_uv', 'none')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "varnish_type" "public"."orders_varnish_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "varnish_details" text`);
        await queryRunner.query(`CREATE TYPE "public"."orders_lamination_type_enum" AS ENUM('shine', 'matt', 'metalize', 'rainbow', 'none')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "lamination_type" "public"."orders_lamination_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "lamination_size" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "uv_emboss_details" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "has_back_printing" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "has_barcode" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "batch_number" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "ctp_info" text`);
        await queryRunner.query(`CREATE TYPE "public"."orders_die_type_enum" AS ENUM('new_die', 'old_die', 'none')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "die_type" "public"."orders_die_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "die_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "emboss_film_details" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "plate_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "designer_name" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "design_approved_by" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "design_approved_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cylinder_reference" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cylinder_sent_date" date`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cylinder_approved_date" date`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "cylinder_received_date" date`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "thickness_micron" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "tablet_size" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "punch_size" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'sales', 'planner', 'accounts', 'inventory')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'sales'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."order_status_enum" RENAME TO "order_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'approved', 'in_production', 'completed', 'delivered', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum" USING "status"::"text"::"public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."order_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."order_priority_enum" RENAME TO "order_priority_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_priority_enum" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" TYPE "public"."orders_priority_enum" USING "priority"::"text"::"public"."orders_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" SET DEFAULT 'normal'`);
        await queryRunner.query(`DROP TYPE "public"."order_priority_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."printing_type_enum" RENAME TO "printing_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_printing_type_enum" AS ENUM('offset', 'digital', 'flexo')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "printing_type" TYPE "public"."orders_printing_type_enum" USING "printing_type"::"text"::"public"."orders_printing_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."printing_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "customer_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."production_job_status_enum" RENAME TO "production_job_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."production_jobs_status_enum" AS ENUM('queued', 'in_progress', 'paused', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" TYPE "public"."production_jobs_status_enum" USING "status"::"text"::"public"."production_jobs_status_enum"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."production_job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "order_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."inventory_category_enum" RENAME TO "inventory_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_items_category_enum" AS ENUM('paper', 'ink', 'plates', 'finishing_materials', 'packaging')`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ALTER COLUMN "category" TYPE "public"."inventory_items_category_enum" USING "category"::"text"::"public"."inventory_items_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_category_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_type_enum" RENAME TO "transaction_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."stock_transactions_transaction_type_enum" AS ENUM('stock_in', 'stock_out', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "transaction_type" TYPE "public"."stock_transactions_transaction_type_enum" USING "transaction_type"::"text"::"public"."stock_transactions_transaction_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."reference_type_enum" RENAME TO "reference_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."stock_transactions_reference_type_enum" AS ENUM('purchase', 'production_job', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "reference_type" TYPE "public"."stock_transactions_reference_type_enum" USING "reference_type"::"text"::"public"."stock_transactions_reference_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reference_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "item_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."cost_type_enum" RENAME TO "cost_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."job_costs_cost_type_enum" AS ENUM('material', 'labor', 'machine', 'overhead')`);
        await queryRunner.query(`ALTER TABLE "job_costs" ALTER COLUMN "cost_type" TYPE "public"."job_costs_cost_type_enum" USING "cost_type"::"text"::"public"."job_costs_cost_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cost_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "job_costs" ALTER COLUMN "job_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status_enum" RENAME TO "invoice_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoices_status_enum" USING "status"::"text"::"public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoice_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "order_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "customer_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ALTER COLUMN "invoice_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_8f138f284609b045dc64c91757a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_574a2f0932043d4e4baf188ee05" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ADD CONSTRAINT "FK_53931cf9bdae6756ee8502017a1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ADD CONSTRAINT "FK_96e40dbd1fd777a611b86af5ebb" FOREIGN KEY ("assigned_operator") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ADD CONSTRAINT "FK_9a3163210dc85e8862360eb2317" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ADD CONSTRAINT "FK_c36f71170f7013658ee98fcc7dd" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_costs" ADD CONSTRAINT "FK_8dedf043a7b1cf9ad001812920b" FOREIGN KEY ("job_id") REFERENCES "production_jobs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_costs" ADD CONSTRAINT "FK_2197f37f0bfcd775ff292004042" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ea83c3b911906a3578de2340fdf" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ea83c3b911906a3578de2340fdf"`);
        await queryRunner.query(`ALTER TABLE "job_costs" DROP CONSTRAINT "FK_2197f37f0bfcd775ff292004042"`);
        await queryRunner.query(`ALTER TABLE "job_costs" DROP CONSTRAINT "FK_8dedf043a7b1cf9ad001812920b"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" DROP CONSTRAINT "FK_c36f71170f7013658ee98fcc7dd"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" DROP CONSTRAINT "FK_9a3163210dc85e8862360eb2317"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" DROP CONSTRAINT "FK_96e40dbd1fd777a611b86af5ebb"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" DROP CONSTRAINT "FK_53931cf9bdae6756ee8502017a1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_574a2f0932043d4e4baf188ee05"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_8f138f284609b045dc64c91757a"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ALTER COLUMN "invoice_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "customer_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "order_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_status_enum_old" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" TYPE "public"."invoice_status_enum_old" USING "status"::"text"::"public"."invoice_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "invoices" ALTER COLUMN "status" SET DEFAULT 'draft'`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."invoice_status_enum_old" RENAME TO "invoice_status_enum"`);
        await queryRunner.query(`ALTER TABLE "job_costs" ALTER COLUMN "job_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."cost_type_enum_old" AS ENUM('material', 'labor', 'machine', 'overhead')`);
        await queryRunner.query(`ALTER TABLE "job_costs" ALTER COLUMN "cost_type" TYPE "public"."cost_type_enum_old" USING "cost_type"::"text"::"public"."cost_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."job_costs_cost_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."cost_type_enum_old" RENAME TO "cost_type_enum"`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "item_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."reference_type_enum_old" AS ENUM('purchase', 'production_job', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "reference_type" TYPE "public"."reference_type_enum_old" USING "reference_type"::"text"::"public"."reference_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."stock_transactions_reference_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."reference_type_enum_old" RENAME TO "reference_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."transaction_type_enum_old" AS ENUM('stock_in', 'stock_out', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ALTER COLUMN "transaction_type" TYPE "public"."transaction_type_enum_old" USING "transaction_type"::"text"::"public"."transaction_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."stock_transactions_transaction_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."transaction_type_enum_old" RENAME TO "transaction_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_category_enum_old" AS ENUM('paper', 'ink', 'plates', 'finishing_materials', 'packaging')`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ALTER COLUMN "category" TYPE "public"."inventory_category_enum_old" USING "category"::"text"::"public"."inventory_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_items_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."inventory_category_enum_old" RENAME TO "inventory_category_enum"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "order_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."production_job_status_enum_old" AS ENUM('queued', 'in_progress', 'paused', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" TYPE "public"."production_job_status_enum_old" USING "status"::"text"::"public"."production_job_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ALTER COLUMN "status" SET DEFAULT 'queued'`);
        await queryRunner.query(`DROP TYPE "public"."production_jobs_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."production_job_status_enum_old" RENAME TO "production_job_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "customer_id" SET NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."printing_type_enum_old" AS ENUM('offset', 'digital', 'flexo')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "printing_type" TYPE "public"."printing_type_enum_old" USING "printing_type"::"text"::"public"."printing_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."orders_printing_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."printing_type_enum_old" RENAME TO "printing_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."order_priority_enum_old" AS ENUM('low', 'normal', 'high', 'urgent')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" TYPE "public"."order_priority_enum_old" USING "priority"::"text"::"public"."order_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "priority" SET DEFAULT 'normal'`);
        await queryRunner.query(`DROP TYPE "public"."orders_priority_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_priority_enum_old" RENAME TO "order_priority_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_enum_old" AS ENUM('pending', 'approved', 'in_production', 'completed', 'delivered', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."order_status_enum_old" USING "status"::"text"::"public"."order_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_status_enum_old" RENAME TO "order_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('admin', 'sales', 'planner', 'accounts', 'inventory')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'sales'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "punch_size"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "tablet_size"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "thickness_micron"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cylinder_received_date"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cylinder_approved_date"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cylinder_sent_date"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "cylinder_reference"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "design_approved_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "design_approved_by"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "designer_name"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "plate_reference"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "emboss_film_details"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "die_reference"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "die_type"`);
        await queryRunner.query(`DROP TYPE "public"."orders_die_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "ctp_info"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "batch_number"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "has_barcode"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "has_back_printing"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "uv_emboss_details"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "lamination_size"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "lamination_type"`);
        await queryRunner.query(`DROP TYPE "public"."orders_lamination_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "varnish_details"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "varnish_type"`);
        await queryRunner.query(`DROP TYPE "public"."orders_varnish_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "color_p4"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "color_p3"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "color_p2"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "color_p1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "color_cmyk"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "strength"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "card_size"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "previous_order_id"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "is_repeat_order"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "product_type"`);
        await queryRunner.query(`DROP TYPE "public"."orders_product_type_enum"`);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_item_invoice" ON "invoice_items" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_date" ON "invoices" ("invoice_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_customer" ON "invoices" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_invoice_status" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_cost_type" ON "job_costs" ("cost_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_job_cost_job" ON "job_costs" ("job_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transaction_date" ON "stock_transactions" ("transaction_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_stock_transaction_item" ON "stock_transactions" ("item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_item_name" ON "inventory_items" ("item_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_inventory_item_category" ON "inventory_items" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_production_job_scheduled_start" ON "production_jobs" ("scheduled_start_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_production_job_order" ON "production_jobs" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_production_job_status" ON "production_jobs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_date" ON "orders" ("order_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_customer" ON "orders" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_order_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_email" ON "customers" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_customer_name" ON "customers" ("name") `);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_invoice_item_invoice" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoice_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoice_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_invoice_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_costs" ADD CONSTRAINT "FK_job_cost_item" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_costs" ADD CONSTRAINT "FK_job_cost_job" FOREIGN KEY ("job_id") REFERENCES "production_jobs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ADD CONSTRAINT "FK_stock_transaction_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transactions" ADD CONSTRAINT "FK_stock_transaction_item" FOREIGN KEY ("item_id") REFERENCES "inventory_items"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ADD CONSTRAINT "FK_production_job_operator" FOREIGN KEY ("assigned_operator") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "production_jobs" ADD CONSTRAINT "FK_production_job_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_order_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_order_customer" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_customer_created_by" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
