// Icon mapping utility for consistent icon usage across the app

import {
  Users,
  FileText,
  Package,
  Factory,
  Clipboard,
  Zap,
  Truck,
  Box,
  DollarSign,
  BarChart3,
  Settings,
  Home,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  Info,
  Clock,
  Calendar,
  MapPin,
  Phone,
  Mail,
  LogOut,
  User,
  Bell,
  Filter,
  Download,
  Upload,
  Copy,
  Share2,
  MoreVertical,
  MoreHorizontal,
  Loader,
  CheckCircle,
  XCircle,
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  BarChart,
  Activity,
  Briefcase,
  ShoppingCart,
  Layers,
  Grid,
  List,
  Maximize2,
  Minimize2,
  RefreshCw,
  Pause,
  Play,
  SkipForward,
  GitBranch,
  Tag,
  Bookmark,
  Star,
  Heart,
  MessageSquare,
  Send,
  Paperclip,
  Wind,
  Droplet,
  Printer,
  Wrench,
  Hammer,
  Cog,
  Sliders,
  Volume2,
  Wifi,
  WifiOff,
  Navigation,
  Compass,
  Map,
  Maximize,
  Minimize,
  RotateCw,
  RotateCcw,
  Repeat,
  Repeat2,
  Shuffle,
  Rewind,
  FastForward,
  SkipBack,
  Mic,
  MicOff,
  Cast,
  Radio,
  Bluetooth,
  Cpu,
  HardDrive,
  Database,
  Server,
  Smartphone,
  Tablet,
  Monitor,
  Tv,
  Watch,
  Headphones,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Music,
  Disc,
  Inbox,
  Trash,
  Archive,
  Flag,
  Rss,
  ExternalLink,
  Link,
  Link2,
  Unlink,
  Anchor,
  Aperture,
} from 'lucide-react';

// Module icons
export const MODULE_ICONS = {
  customers: Users,
  quotations: FileText,
  orders: Package,
  production: Factory,
  planning: Clipboard,
  'shop-floor': Zap,
  dispatch: Truck,
  inventory: Box,
  costing: DollarSign,
  invoices: BarChart3,
  quality: CheckCircle,
  wastage: AlertTriangle,
  users: Users,
  dashboard: Home,
} as const;

// UI icons
export const UI_ICONS = {
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  search: Search,
  plus: Plus,
  edit: Edit,
  delete: Trash2,
  view: Eye,
  hide: EyeOff,
  check: Check,
  alert: AlertCircle,
  info: Info,
  clock: Clock,
  calendar: Calendar,
  location: MapPin,
  phone: Phone,
  email: Mail,
  logout: LogOut,
  user: User,
  notifications: Bell,
  filter: Filter,
  download: Download,
  upload: Upload,
  copy: Copy,
  share: Share2,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  loading: Loader,
  success: CheckCircle,
  error: XCircle,
  warning: AlertTriangle,
  trending: TrendingUp,
  chart: BarChart,
  settings: Settings,
  grid: Grid,
  list: List,
  refresh: RefreshCw,
  pause: Pause,
  play: Play,
  skip: SkipForward,
  tag: Tag,
  bookmark: Bookmark,
  star: Star,
  message: MessageSquare,
  send: Send,
  attachment: Paperclip,
  wrench: Wrench,
  cog: Cog,
  sliders: Sliders,
  maximize: Maximize2,
  minimize: Minimize2,
  repeat: Repeat,
  rewind: Rewind,
  fastForward: FastForward,
  shuffle: Shuffle,
  volume: Volume2,
  wifi: Wifi,
  wifiOff: WifiOff,
  navigation: Navigation,
  compass: Compass,
  map: Map,
  rotateRight: RotateCw,
  rotateLeft: RotateCcw,
  mic: Mic,
  micOff: MicOff,
  bluetooth: Bluetooth,
  cpu: Cpu,
  hardDrive: HardDrive,
  database: Database,
  server: Server,
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  tv: Tv,
  watch: Watch,
  headphones: Headphones,
  camera: Camera,
  cameraOff: CameraOff,
  video: Video,
  videoOff: VideoOff,
  music: Music,
  disc: Disc,
  inbox: Inbox,
  mailOpen: Mail,
  sendMail: Send,
  trash: Trash,
  archive: Archive,
  flag: Flag,
  rss: Rss,
  externalLink: ExternalLink,
  link: Link,
  link2: Link2,
  unlink: Unlink,
  anchor: Anchor,
  aperture: Aperture,
  activity: Activity,
  briefcase: Briefcase,
  shoppingCart: ShoppingCart,
  layers: Layers,
  pieChart: PieChart,
  lineChart: LineChart,
  trendingDown: TrendingDown,
  printer: Printer,
  hammer: Hammer,
} as const;

// Status icons
export const STATUS_ICONS = {
  pending: Clock,
  approved: Check,
  in_progress: Zap,
  completed: CheckCircle,
  delivered: CheckCircle,
  cancelled: XCircle,
  rejected: XCircle,
  paused: Pause,
  queued: Clock,
  error: AlertCircle,
  warning: AlertTriangle,
  success: CheckCircle,
  info: Info,
} as const;

// Get icon by name
export function getIcon(name: keyof typeof UI_ICONS | keyof typeof MODULE_ICONS | keyof typeof STATUS_ICONS) {
  return UI_ICONS[name as keyof typeof UI_ICONS] ||
         MODULE_ICONS[name as keyof typeof MODULE_ICONS] ||
         STATUS_ICONS[name as keyof typeof STATUS_ICONS];
}

// Export all icons for direct usage
export {
  Users,
  FileText,
  Package,
  Factory,
  Clipboard,
  Zap,
  Truck,
  Box,
  DollarSign,
  BarChart3,
  Settings,
  Home,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Check,
  AlertCircle,
  Info,
  Clock,
  Calendar,
  MapPin,
  Phone,
  Mail,
  LogOut,
  User,
  Bell,
  Filter,
  Download,
  Upload,
  Copy,
  Share2,
  MoreVertical,
  MoreHorizontal,
  Loader,
  CheckCircle,
  XCircle,
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  PieChart,
  LineChart,
  BarChart,
  Activity,
  Briefcase,
  ShoppingCart,
  Layers,
  Grid,
  List,
  Maximize2,
  Minimize2,
  RefreshCw,
  Pause,
  Play,
  SkipForward,
  GitBranch,
  Tag,
  Bookmark,
  Star,
  Heart,
  MessageSquare,
  Send,
  Paperclip,
  Wind,
  Droplet,
  Printer,
  Wrench,
  Hammer,
  Cog,
  Sliders,
  Volume2,
  Wifi,
  WifiOff,
  Navigation,
  Compass,
  Map,
  Maximize,
  Minimize,
  RotateCw,
  RotateCcw,
  Repeat,
  Repeat2,
  Shuffle,
  Rewind,
  FastForward,
  SkipBack,
  Mic,
  MicOff,
  Cast,
  Radio,
  Bluetooth,
  Cpu,
  HardDrive,
  Database,
  Server,
  Smartphone,
  Tablet,
  Monitor,
  Tv,
  Watch,
  Headphones,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Music,
  Disc,
  Inbox,
  Trash,
  Archive,
  Flag,
  Rss,
  ExternalLink,
  Link,
  Link2,
  Unlink,
  Anchor,
  Aperture,
};
